services:
  app:
    build: .
    container_name: shopping-cart-app
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    image: postgres:16
    container_name: shopping-cart-db
    environment:
      POSTGRES_USER: sai
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: shoppingcart
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: